from building import *

cwd = GetCurrentDir()
src = Glob('common/proto/*.c')
src += Glob('common/protobuf-c/protobuf-c/*.c')
src += Glob('host/api/src/*.c')
src += Glob('host/drivers/rpc/core/*.c')
src += Glob('host/drivers/rpc/slaveif/*.c')
src += Glob('host/drivers/rpc/wrap/*.c')
src += Glob('host/drivers/transport/*.c')
src += Glob('host/port/rtsmart/*.c')

CPPPATH = [
    cwd,
    cwd + '/common/proto',
    cwd + '/common/protobuf-c',
    cwd + '/host/api/include',
    cwd + '/host/api/priv',
    cwd + '/host/drivers/rpc/core',
    cwd + '/host/drivers/rpc/slaveif',
    cwd + '/host/drivers/rpc/wrap',
    cwd + '/host/drivers/transport',
    cwd + '/host/port/rtsmart',
]

group = DefineGroup('esp_hosted', src, depend=['RT_USING_ESP_HOSTED'],
                    CPPPATH=CPPPATH)

Return('group')
