#define _LARGEFILE64_SOURCE
#define _FILE_OFFSET_BITS 64

#include <rtconfig.h>
#include "custom_buildconf.h"

#ifndef CONFIG_READ_FILE_BUFFER_SIZE
#ifdef MTP_READ_FILE_BUFFER_SIZE
#define CONFIG_READ_FILE_BUFFER_SIZE MTP_READ_FILE_BUFFER_SIZE
#else
#define CONFIG_READ_FILE_BUFFER_SIZE (512*1024)
#endif
#endif

#ifndef CONFIG_MAX_TX_USB_BUFFER_SIZE
#ifdef MTP_MAX_TX_USB_BUFFER_SIZE
#define CONFIG_MAX_TX_USB_BUFFER_SIZE MTP_MAX_TX_USB_BUFFER_SIZE
#else
#define CONFIG_MAX_TX_USB_BUFFER_SIZE (256*1024)
#endif
#endif

#ifndef CONFIG_MAX_RX_USB_BUFFER_SIZE
#ifdef MTP_MAX_RX_USB_BUFFER_SIZE
#define CONFIG_MAX_RX_USB_BUFFER_SIZE MTP_MAX_RX_USB_BUFFER_SIZE
#else
#define CONFIG_MAX_RX_USB_BUFFER_SIZE (256*1024)
#endif
#endif

#ifndef CONFIG_FS_DB_CACHE_BUCKETS
#ifdef MTP_FS_DB_CACHE_BUCKETS
#define CONFIG_FS_DB_CACHE_BUCKETS MTP_FS_DB_CACHE_BUCKETS
#else
#define CONFIG_FS_DB_CACHE_BUCKETS (16*1024)
#endif
#endif

#ifndef CONFIG_FS_DB_POOL_SIZE
#ifdef MTP_FS_DB_POOL_SIZE
#define CONFIG_FS_DB_POOL_SIZE MTP_FS_DB_POOL_SIZE
#else
#define CONFIG_FS_DB_POOL_SIZE (256*1024)
#endif
#endif

#ifndef CONFIG_FS_DB_SCAN_CACHE
#ifdef MTP_FS_DB_SCAN_CACHE_VALUE
#define CONFIG_FS_DB_SCAN_CACHE MTP_FS_DB_SCAN_CACHE_VALUE
#else
#define CONFIG_FS_DB_SCAN_CACHE 1
#endif
#endif

#ifndef CONFIG_MTP_DIR_READ_BUFFER_SIZE
#ifdef MTP_DIR_READ_BUFFER_SIZE
#define CONFIG_MTP_DIR_READ_BUFFER_SIZE MTP_DIR_READ_BUFFER_SIZE
#else
#define CONFIG_MTP_DIR_READ_BUFFER_SIZE (32*1024)
#endif
#endif
